ALTER TABLE beneficiaries ADD COLUMN IF NOT EXISTS client_id VARCHAR(36) UNIQUE;
ALTER TABLE children ADD COLUMN IF NOT EXISTS client_id VARCHAR(36) UNIQUE;
ALTER TABLE visits ADD COLUMN IF NOT EXISTS client_id VARCHAR(36) UNIQUE;
ALTER TABLE asha_reports ADD COLUMN IF NOT EXISTS client_id VARCHAR(36) UNIQUE;
ALTER TABLE family_members ADD COLUMN IF NOT EXISTS client_id VARCHAR(36) UNIQUE;
ALTER TABLE vaccinations ADD COLUMN IF NOT EXISTS client_id VARCHAR(36) UNIQUE;
ALTER TABLE growth_measurements ADD COLUMN IF NOT EXISTS client_id VARCHAR(36) UNIQUE;
